name: Go Technical Test CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.21"

    - name: Verify build
      run: |
        go mod tidy
        go build ./...

    - name: Run Technical Test
      run: |
        go run . > technical_test.txt

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: technical_test_output
        path: technical_test.txt